[profile.default]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
optimizer = true
optimizer_runs = 100000

# pre push0 for maximum compatibility
evm_version = "paris"

remappings = [
    "forge-std/=lib/rain.verify.interface/lib/forge-std/src/",
    "rain.deploy/=lib/rain.deploy/src/",
    "rain.factory/=lib/rain.factory/src/",
    "rain.interpreter.interface/=lib/rain.interpreter.interface/src/",
    "rain.sol.codegen/=lib/rain.interpreter.interface/lib/rain.sol.codegen/src/",
    "rain.verify.interface/=lib/rain.verify.interface/src/",
]

bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [{ access = "read-write", path = "./src/generated"}]

[rpc_endpoints]
arbitrum = "${CI_DEPLOY_ARBITRUM_RPC_URL}"
base = "${CI_DEPLOY_BASE_RPC_URL}"
base_sepolia = "${CI_DEPLOY_BASE_SEPOLIA_RPC_URL}"
flare = "${CI_DEPLOY_FLARE_RPC_URL}"
polygon = "${CI_DEPLOY_POLYGON_RPC_URL}"

[etherscan]
arbitrum = { key = "${CI_DEPLOY_ARBITRUM_ETHERSCAN_API_KEY}" }
base = { key = "${CI_DEPLOY_BASE_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${CI_DEPLOY_BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
flare = { key = "${CI_DEPLOY_FLARE_ETHERSCAN_API_KEY}" }
polygon = { key = "${CI_DEPLOY_POLYGON_ETHERSCAN_API_KEY}" }