version = 1

[[annotations]]
path = [
    ".github/workflows/**/",
    ".gitignore",
]
SPDX-FileCopyrightText = "Copyright (c) 2020 Rain Open Source Software Ltd"
SPDX-License-Identifier = "LicenseRef-DCL-1.0"
